version: '3'

services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis

  db:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=shop_db
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    
  celery_worker:
    build: .
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - db
    command: celery -A shop_api worker --loglevel=info
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis

  celery_beat:
    build: .
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - db
      - celery_worker
    command: celery -A shop_api beat --loglevel=info
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis

volumes:
  postgres_data:
  redis_data: