# Generated by Django 4.2.23 on 2025-07-04 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='ConfirmationCode',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
